### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by tomscytale**
`slugField` is undefined here

### CODE REVIEW

**Comment by Systerr** [comment]
I also found this bug, but most curious for me - it work before last mongoose (?) releases. What changed?

**Comment by tomscytale** [comment]
@talha-asad could you merge this please - it's a very simple and obvious fix.

**Comment by tomscytale** [comment]
@talha-asad that's great - thanks very much. Could you push version 1.0.3 to npm?

**Comment by tomscytale** [comment]
@talha-asad - could you do a release to npm pls?

**Pull request merged**
